export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Custom404 } from './Custom404';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as History } from './History';
export { default as Home } from './Home';
export { default as LogIn } from './LogIn';
export { default as LoginModal } from './LoginModal';